version: '2'
services:
    tdxmain-app:
        image: tdxmain
        external_links:
            - tdxmain-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/tdxmain
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tdxmain-postgresql:
        extends:
            file: postgresql.yml
            service: tdxmain-postgresql
